logging.level.org.springframework.cloud.kubernetes: DEBUG
spring.application.name: config-example
spring.cloud.kubernetes.config.namespace: default

management:
  endpoints:
    web:
      exposure:
        include: info,refresh,keepalive,health
