logging.level.org.springframework.cloud.kubernetes: DEBUG
welcome.message: hola desde mi app properties
welcome.lala: lala

spring.application.name: config-example
spring.cloud.kubernetes.config.namespace: default
spring.cloud.kubernetes.reload.period: 15000
spring.cloud.kubernetes.reload.enabled: true
spring.cloud.kubernetes.reload.mode: POLLING

management:
  endpoint:
    restart:
      enabled: true
